### PR TITLE
feat: make instance iframes resizeable

### PR DESCRIPTION
**Pull request by WofWca**

### CODE REVIEW

**Comment by adbenitez** [comment]
@WofWca mmmmh thinking a bit about this, I don't think it is necessary, because the emulator already supports opening the instances in a new tab, then you can use there proper mobile screen tools from the browser's developer tools with proper "tap" emulation

**Comment by WofWca** [comment]
You can, but I think this feature is not just for writing CSS for different screen sizes. It's for more customized interaction testing setup.

**Comment by adbenitez** [comment]
I don't understand what you mean, but as I commented, you can already resize the app at taste opening in a new tab, there is no need for superfluous features, allowing to resize the iframe opens the door for mistakes like the user accidentally changing size then there is not a button to reset size etc. and the gain of resizing the emulator instances iframes is low and ugly

**Comment by WofWca** [comment]
I'm saying that I understand that you can resize the window in a separate tab, but you may still want to also do it on the main page of this tool. For example, when you have your code editor on the right on your monitor an the `webxdc-dev` tab on the left, and two (or more) app instances don't quite fit in one row because they're too wide.

I don't think this feature is big enough to worry about potential future problems. It can easily be removed if they do arise.

**Comment by adbenitez** [comment]
> For example, when you have your code editor on the right on your monitor an the `webxdc-dev` tab on the left, and two (or more) app instances don't quite fit in one row because they're too wide.
> 
> I don't think this feature is big enough to worry about potential future problems. It can easily be removed if they do arise.

you can already do that today, with the feature of opening the frame in a new tab, you can open, lets say two frames, in a new tab then use the feature of your browser to detach the tabs in new windows and you can have your editor in one side while having the other two windows using half of the other side both

closing stale +1yo PR

**Pull request closed without merging**
